### PR TITLE
Laser sword

### PR DESCRIPTION
**Pull request by wdnmdren**
I finish the model for the pickaxe and submit the _P.pak file.

### CODE REVIEW

**Comment by Patch4747** [comment]
The game crashes when I try to include this mod. Did you test? Does this work on your machine?

**Comment by wdnmdren** [comment]
I don't know why, the file work perfect on my machine.

**Comment by wdnmdren** [comment]
I put it in the Steam\steamapps\common\Deep Rock Galactic\FSD\Mods\TestMod

**Comment by JoshuaMarion** [comment]
This worked for me locally

**Pull request merged**
